version: '1.0.0-{build}'
image: Ubuntu

clone_depth: 1

branches:
  only:
    - master

skip_commits:
  message: /.*\[ci skip\].*/

build_script:
  - sh: dotnet publish ./src/BibleBot.Backend/BibleBot.Backend.csproj --verbosity q
  - sh: dotnet build ./src/BibleBot.Lib/BibleBot.Lib.csproj --verbosity q
  - sh: nuget pack ./src/BibleBot.Lib/ -Verbosity quiet

artifacts:
  - path: ./src/BibleBot.Backend/bin/Debug/net5.0/publish
    name: BibleBot.Backend
    type: ElasticBeanstalkPackage
  
  - path: '*.nupkg'
    type: NuGetPackage

test_script:
  - sh: dotnet test --verbosity m

deploy:
  - provider: NuGet
    api_key:
      secure: 3ldSZooGg5G90viYmQhqpQtGqTftoapjkaoGSim3tB7AmBlRIc/G3IqxAxcksdsP

notifications:
  - provider: Webhook
    url:
      secure: c67RyRJkkEc4YgxUskPhCmMtxWdEUsrswCKA2ApLb3tZ72seTIPNzQfilxcJ+pRJMlNUkVpO8zjxqUs/xWPaBHE8+vBMWLuav9/Y25TyKXyXnRTAnMzkOXDg3RXch8Vlv1Vpsun200mPr1sW4yqIhQK39QG8bskhkEP3bLgsC5w=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true