version: '9.1-beta-{build}'
image: Visual Studio 2019

clone_depth: 1

services:
  - mongodb

environment:
  ASPNETCORE_ENVIRONMENT: Development
  MONGODB_CONN: mongodb://localhost:27017/BibleBotBackend
  WEBHOOK_SCRIPT: https://raw.githubusercontent.com/BibleBot/appveyor-discord-webhook/master/send.ps1
  APIBIBLE_TOKEN:
    secure: NoI3xBuwnbCU1KkhhZCHqtuups493tGwfNZlBNtXvCw8cNuuTvwZZwMYm2V12EvA
  ENDPOINT_TOKEN:
    secure: iHQQcLiFJcSErA/ZLVm5WEaX8kuTrMiZ5Y28JFnmZkY=
  CODACY_PROJECT_TOKEN:
    secure: OzycgsRcoQBRFwoPdQpsV4HiGZazulGy2xMZAK0P3e+ZIL9dW4igdTmUpM3ZCXrf
  DISCORD_WEBHOOK:
    secure: c67RyRJkkEc4YgxUskPhCmMtxWdEUsrswCKA2ApLb3vLH5eSf3G0pawFOhwJEj0cPqoqiGh1v95sc23adle9F6sYA+LCTdHYtiyL3Cz5traiteg2vQavv5pzPuWjxShv7PVsRsF4P77VDIBxthK5Z0ypG6K/A4gKOT3lijFv6oE=

skip_commits:
  message: /.*\[ci skip\].*/

install:
  - cmd: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json
  - cmd: dotnet restore --verbosity q

branches:
  only:
    - master

build_script:
  - cmd: dotnet publish .\src\BibleBot.Backend\BibleBot.Backend.csproj -c Release --verbosity q
  - cmd: dotnet build .\src\BibleBot.Lib\BibleBot.Lib.csproj -c Release --verbosity q
  - cmd: dotnet publish .\src\BibleBot.Frontend\BibleBot.Frontend.csproj -c Release --verbosity q
  - cmd: dotnet pack .\src\BibleBot.Lib -o . -c Release --verbosity q

artifacts:
  - path: .\src\BibleBot.Backend\bin\Release\net5.0\publish
    name: BibleBot.Backend
    type: ElasticBeanstalkPackage
  
  - path: '*.nupkg'
    name: BibleBot.Lib
    type: NuGetPackage

  - path: .\src\BibleBot.Frontend\bin\Release\net5.0\publish
    name: BibleBot.Frontend
    type: ElasticBeanstalkPackage

test_script:
  - "%USERPROFILE%\\.nuget\\packages\\opencover\\4.7.1221\\tools\\OpenCover.Console.exe -register:user -target:\"dotnet.exe\" -targetargs:\"test --verbosity q --logger:\\\"trx;LogFileName=..\\..\\..\\TestResults.xml\\\"\" -output:\"coverage.xml\" -oldStyle -filter:\"+[BibleBot.Backend*]* -[BibleBot.Backend.Tests*]*\" >nul"

after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://coverage.codacy.com/get.sh' -OutFile codacy.sh
  - cmd: bash codacy.sh report -r "coverage.xml" >nul
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResults.xml))

deploy:
  - provider: NuGet
    api_key:
      secure: 3ldSZooGg5G90viYmQhqpQtGqTftoapjkaoGSim3tB7AmBlRIc/G3IqxAxcksdsP

on_success:
  - ps: Invoke-RestMethod $env:WEBHOOK_SCRIPT -o send.ps1
  - ps: .\send.ps1 success $env:DISCORD_WEBHOOK
on_failure:
  - ps: Invoke-RestMethod $env:WEBHOOK_SCRIPT -o send.ps1
  - ps: .\send.ps1 failure $env:DISCORD_WEBHOOK