commit_message: "style: updates to %original_file_name% for %language%"
append_commit_message: false
pull_request_title: "style: crowdin updates"
files:
  - source: /src/**/Resources/**/*.resx
    ignore:
      - /src/**/Resources/**/*.*.resx
    translation: /src/**/Resources/**/%file_name%.%locale%.resx
  - source: /src/BibleBot.Frontend/default_i18n.json
    translation: /src/BibleBot.Frontend/locale/%two_letters_code%.json
