commit_message: "[ci skip]"
append_commit_message:
files:
  - source: /src/**/Resources/**/*.resx
    ignore:
      - /src/**/Resources/**/*.*.resx
    translation: /src/**/Resources/**/%file_name%.%locale%.resx
  - source: /src/BibleBot.Frontend/locale/default.json
    translation: /src/BibleBot.Frontend/locale/%locale%.json
