files:
  - source: /i18n/default/default.json
    translation: /i18n/%language%/%language%.json
    languages_mapping:
      language:
        af: afrikaans
        sq: albanian
        am: amharic
        ar: arabic
        hy-AM: armenian
        az: azerbaijani
        eu: basque
        be: belarusian
        bn: bengali
        br-FR: breton
        bg: bulgarian
        ca: catalan
        ce: chechen
        zh-CN: chinese_simp
        zh-TW: chinese_trad
        cs: czech
        da: danish
        nl: dutch
        en-GB: english_uk
        en-US: english_us
        eo: esperanto
        fil: filipino
        fi: finnish
        fr: french
        fr-QC: french_qc
        de: german
        de-AT: german_at
        de-CH: german_ch
        el: greek
        he: hebrew
        hi: hindi
        hu: hungarian
        id: indonesian
        ga-IE: irish
        it: italian
        ja: japanese
        ko: korean
        jbo: lojban
        no: norwegian
        pl: polish
        pt-PT: portuguese
        pt-BR: portuguese_br
        pa-IN: punjabi
        pa-PK: punjabi_pk
        ro: romanian
        ru: russian
        sco: scots
        gd: scottish_gaelic
        sr: serbian_cyr
        si-LK: sinhala
        sk: slovak
        es-ES: spanish
        sv-SE: swedish
        syc: syriac
        tl: tagalog
        th: thai
        bo-BT: tibetan
        tr: turkish
        uk: ukrainian
        ur-IN: urdu_in
        ur-PK: urdu_pk
        vi: vietnamese
        cy: welsh
