// <auto-generated />
using System.Collections.Generic;
using BibleBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace BibleBot.Models.Migrations
{
    [DbContext(typeof(PgContext))]
    partial class PgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BibleBot.Models.AppendedVerse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("VerseMetricId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_metric_id");

                    b.Property<NpgsqlRange<int>>("VerseRange")
                        .HasColumnType("int4range")
                        .HasColumnName("verse_range");

                    b.HasKey("Id");

                    b.HasIndex("VerseMetricId")
                        .HasDatabaseName("idx_appended_verse_metric_id");

                    b.ToTable("appended_verses", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalName")
                        .HasColumnType("text")
                        .HasColumnName("internal_name");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PreferredName")
                        .HasColumnType("text")
                        .HasColumnName("preferred_name");

                    b.Property<string>("ProperName")
                        .HasColumnType("text")
                        .HasColumnName("proper_name");

                    b.Property<string>("VersionId")
                        .HasColumnType("text")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Name")
                        .IsUnique();

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<List<ChapterTitle>>("Titles")
                        .HasColumnType("jsonb")
                        .HasColumnName("titles");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Number")
                        .IsUnique();

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Experiment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<ExperimentFeedback>("Feedback")
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback");

                    b.Property<string>("Sphere")
                        .HasColumnType("text")
                        .HasColumnName("sphere");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.PrimitiveCollection<string>("Variants")
                        .HasColumnType("jsonb")
                        .HasColumnName("variants");

                    b.PrimitiveCollection<string>("Weights")
                        .HasColumnType("jsonb")
                        .HasColumnName("weights");

                    b.HasKey("Id");

                    b.ToTable("experiments", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.FrontendStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelCount")
                        .HasColumnType("integer")
                        .HasColumnName("channel_count");

                    b.Property<string>("FrontendRepoCommitHash")
                        .HasColumnType("text")
                        .HasColumnName("commit_hash");

                    b.Property<int>("ServerCount")
                        .HasColumnType("integer")
                        .HasColumnName("server_count");

                    b.Property<int>("ShardCount")
                        .HasColumnType("integer")
                        .HasColumnName("shard_count");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer")
                        .HasColumnName("user_count");

                    b.Property<int>("UserInstallCount")
                        .HasColumnType("integer")
                        .HasColumnName("user_install_count");

                    b.HasKey("Id");

                    b.ToTable("frontend_stats", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Guild", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("DailyVerseChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("dv_channel_id");

                    b.Property<bool>("DailyVerseIsThread")
                        .HasColumnType("boolean")
                        .HasColumnName("dv_is_thread");

                    b.Property<string>("DailyVerseLastSentDate")
                        .HasColumnType("text")
                        .HasColumnName("dv_last_sent");

                    b.Property<int>("DailyVerseLastStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("dv_last_status");

                    b.Property<long>("DailyVerseRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("dv_role_id");

                    b.Property<string>("DailyVerseTime")
                        .HasColumnType("text")
                        .HasColumnName("dv_time");

                    b.Property<string>("DailyVerseTimeZone")
                        .HasColumnType("text")
                        .HasColumnName("dv_timezone");

                    b.Property<string>("DailyVerseWebhook")
                        .HasColumnType("text")
                        .HasColumnName("dv_webhook");

                    b.Property<string>("DisplayStyle")
                        .HasColumnType("text")
                        .HasColumnName("display_style");

                    b.Property<string>("IgnoringBrackets")
                        .HasColumnType("text")
                        .HasColumnName("ignoring_brackets");

                    b.Property<bool>("IsDM")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dm");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DailyVerseLastSentDate")
                        .HasDatabaseName("idx_guilds_dv_last_sent");

                    b.HasIndex("DailyVerseTime", "DailyVerseTimeZone")
                        .HasDatabaseName("idx_guilds_daily_verse")
                        .HasFilter("\"dv_webhook\" IS NOT NULL");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DefaultVersion")
                        .HasColumnType("text")
                        .HasColumnName("default_version");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.OptOutUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("opt_out_users", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("DisplayStyle")
                        .HasColumnType("text")
                        .HasColumnName("display_style");

                    b.Property<string>("InputMethod")
                        .HasColumnType("text")
                        .HasColumnName("input_method");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<bool>("PaginationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pagination_enabled");

                    b.Property<bool>("TitlesEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("titles_enabled");

                    b.Property<bool>("VerseNumbersEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("verse_numbers_enabled");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Language")
                        .HasDatabaseName("idx_users_language");

                    b.HasIndex("Version")
                        .HasDatabaseName("idx_users_version");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("verses", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.VerseMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsDEU")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deu");

                    b.Property<bool>("IsNT")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nt");

                    b.Property<bool>("IsOT")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ot");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<Instant>("TimeGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_generated")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<NpgsqlRange<int>>("VerseRange")
                        .HasColumnType("int4range")
                        .HasColumnName("verse_range");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TimeGenerated")
                        .IsDescending()
                        .HasDatabaseName("idx_verse_metrics_time_generated");

                    b.HasIndex("GuildId", "Book", "Chapter")
                        .HasDatabaseName("idx_verse_metrics_guild_book_chapter");

                    b.HasIndex("UserId", "Book", "Chapter")
                        .HasDatabaseName("idx_verse_metrics_user_book_chapter");

                    b.ToTable("verse_metrics", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.Version", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AliasOfId")
                        .HasColumnType("text")
                        .HasColumnName("alias_of_id");

                    b.Property<bool>("FollowsSeptuagintNumbering")
                        .HasColumnType("boolean")
                        .HasColumnName("follows_septuagint");

                    b.Property<string>("InternalId")
                        .HasColumnType("text")
                        .HasColumnName("internal_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<bool>("SupportsDeuterocanon")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_deu");

                    b.Property<bool>("SupportsNewTestament")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_nt");

                    b.Property<bool>("SupportsOldTestament")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_ot");

                    b.HasKey("Id");

                    b.ToTable("versions", (string)null);
                });

            modelBuilder.Entity("BibleBot.Models.AppendedVerse", b =>
                {
                    b.HasOne("BibleBot.Models.VerseMetric", "VerseMetric")
                        .WithMany("AppendedVerses")
                        .HasForeignKey("VerseMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerseMetric");
                });

            modelBuilder.Entity("BibleBot.Models.Book", b =>
                {
                    b.HasOne("BibleBot.Models.Version", null)
                        .WithMany("Books")
                        .HasForeignKey("VersionId");
                });

            modelBuilder.Entity("BibleBot.Models.Chapter", b =>
                {
                    b.HasOne("BibleBot.Models.Book", null)
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibleBot.Models.OptOutUser", b =>
                {
                    b.HasOne("BibleBot.Models.User", null)
                        .WithOne("OptOutEntry")
                        .HasForeignKey("BibleBot.Models.OptOutUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibleBot.Models.Verse", b =>
                {
                    b.HasOne("BibleBot.Models.Chapter", null)
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibleBot.Models.Book", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("BibleBot.Models.Chapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("BibleBot.Models.User", b =>
                {
                    b.Navigation("OptOutEntry");
                });

            modelBuilder.Entity("BibleBot.Models.VerseMetric", b =>
                {
                    b.Navigation("AppendedVerses");
                });

            modelBuilder.Entity("BibleBot.Models.Version", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
