name: Bot Service Issue
description: Chances are, we're already aware of any ongoing service issues.
contact_links:
  - name: Discord Support
    url: https://biblebot.xyz/discord
    about: Join our support Discord to follow along to status updates.