name: Content Request
description: Request a catechism, confession, or historical document to be added to BibleBot!
labels: [content]
assignees:
  - seraphimrp
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this content request!
  - type: textarea
    id: details
    attributes:
      label: What would you like to see implemented in BibleBot?
      description: "**This is not for translations or language requests.**"
      placeholder: I want the bestest catechism evar!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BibleBot/BibleBot/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
