name: Feature Request
description: Request a feature to be added
labels: [feature]
assignees:
  - seraphimrp
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: details
    attributes:
      label: What would you like to see implemented in BibleBot?
      description: "**This is not for translations, languages, or content requests.**"
      placeholder: I want unicorns and lightning!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        By submitting this form, you agree to follow our [Code of Conduct](https://github.com/BibleBot/BibleBot/blob/master/CODE_OF_CONDUCT.md).    
