name: Language Request
description: Request a language to be added to BibleBot!
title: ""
labels: [language]
assignees:
  - seraphimrp
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this language request!
  - type: textarea
    id: details
    attributes:
      label: What language would you like to see implemented in BibleBot?
      description: **This is not for translations or content requests.**
      placeholder: I want Turkish!
      value: ""
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BibleBot/BibleBot/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
