name: Language Request
description: Request a language to be added
labels: [language]
assignees:
  - seraphimrp
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this language request!

        <!-- By submitting this issue, you agree to follow our Code of Conduct: https://github.com/BibleBot/BibleBot/blob/master/CODE_OF_CONDUCT.md -->
  - type: textarea
    id: details
    attributes:
      label: What language would you like to see implemented in BibleBot?
      description: "**This is not for translations or content requests.**"
      placeholder: I want Turkish!
    validations:
      required: true
